fix

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,11 +1,10 @@
-# PHP base container, contiene la base per i container di dev e prod
+# PHP base container
 FROM php:8.2-fpm
 
 # Arguments definiti in docker-compose.yml
 ARG user
 ARG uid
 
-# Imposta la directory di lavoro per le operazioni di root
 WORKDIR /tmp
 
 # Installa dipendenze di sistema
@@ -46,29 +45,24 @@ RUN useradd -G www-data,root -u $uid -d /home/$user $user && \
 # Imposta la directory di lavoro per l'applicazione
 WORKDIR /var/www/laravel
 
-## Copia i file di Composer e installa le dipendenze
-#COPY composer.json composer.lock ./
-#
-## Esegui composer install
-#RUN composer install --no-dev --prefer-dist --optimize-autoloader
+# Copia i file di Composer
+COPY composer.json composer.lock ./
 
-# Copia il resto del codice dell'applicazione
-#COPY . .
+# Debug temporaneo di composer
+RUN composer install --no-dev --prefer-dist --optimize-autoloader || echo "Composer failed but continuing for debugging"
 
 # Imposta i permessi appropriati
 RUN chown -R $user:$user /var/www/laravel
 
 # Copia lo script entrypoint.sh nel container
 COPY docker/entrypoint.sh /usr/local/bin/
-#RUN chmod 755 /usr/local/bin/entrypoint.sh
-
-# Imposta i permessi di esecuzione per entrypoint.sh
-RUN chmod +x /usr/local/bin/entrypoint.sh
+RUN chmod 777 /usr/local/bin/entrypoint.sh
 
 # Espone la porta 9000
 EXPOSE 9000
 
 # Imposta l'entrypoint per lanciare lo script
-#ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
-#
-#CMD ["php-fpm"]
+ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
+
+# Comando default
+CMD ["php-fpm"]
